# Data Alaysis Tutorial

I will be doing a data analysis tutorial so that I can get a firm grasp on `pandas` `numpy` and the `plotly` libraries. The goals of this tutorial will be as follows:

 - Learn how to analyze data statistically using `pandas` and `numpy`.
 - Learn how to vizualize data using `plotly`.
 - Learn how to clean data before analysis.

 I am going to be looking at many sources of data and create data randomly for this project.

 **Let the fun begin.**

In [1]:
import numpy as np
import plotly.express as px
import pandas as pd

In [2]:
# I will be starting off with numpy array.
# ML and Deep Learning has a lot to do with Linear Algebra and Numpy is good.

# np arrays look like a basic python list
# Here is an example

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a[0]) # list indexint still works for np arrays
print(b[0])
print(c.shape) # the.shape attribute will give the dimensions of the array

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

sum_x_y = x + y
print(sum_x_y)

1
5
(3, 3)
[ 6  8 10 12]


In [3]:
# Fill Arrays Automatically

a = np.zeros((5,7,3)) # Gives 5 arrays with a height of 7 and a length of 3
print(a.shape)

b = np.random.random((9,4,2))
print(b)

(5, 7, 3)
[[[0.85374881 0.23149535]
  [0.31135781 0.41881354]
  [0.31283504 0.07621139]
  [0.60203563 0.84293027]]

 [[0.17966283 0.25659642]
  [0.57537378 0.65605303]
  [0.83799704 0.58649248]
  [0.84911655 0.81580846]]

 [[0.76113402 0.00867158]
  [0.39956383 0.85333841]
  [0.41439398 0.70459811]
  [0.53776237 0.08906824]]

 [[0.86031739 0.52082753]
  [0.49704041 0.65255854]
  [0.20630535 0.2488338 ]
  [0.84577193 0.56255727]]

 [[0.81633717 0.33940567]
  [0.592843   0.06960565]
  [0.58273466 0.56190557]
  [0.95272528 0.71896894]]

 [[0.18287298 0.99836717]
  [0.89773146 0.31587262]
  [0.31508192 0.89859113]
  [0.14729242 0.63712041]]

 [[0.59882914 0.9328179 ]
  [0.50813327 0.86493243]
  [0.71661013 0.73363556]
  [0.79782935 0.17723945]]

 [[0.65856715 0.16863623]
  [0.49027933 0.51996811]
  [0.6772285  0.48483407]
  [0.77073586 0.14072679]]

 [[0.62305598 0.51249289]
  [0.53395976 0.60462306]
  [0.28236456 0.88547209]
  [0.45223137 0.97419374]]]


In [4]:
# Rnage Functions

x = np.arange(0,1000,5) # the order is starting val, ending val, step size
y = x*2 - x**2
# print(y)

w = np.linspace(0,1000,100) # starting val, ending val, amount of points specified
z = w*2 - w**2
print(z)

[ 0.00000000e+00 -8.18283849e+01 -3.67717580e+02 -8.57667585e+02
 -1.55167840e+03 -2.44975003e+03 -3.55188246e+03 -4.85807571e+03
 -6.36832976e+03 -8.08264463e+03 -1.00010203e+04 -1.21234568e+04
 -1.44499541e+04 -1.69805122e+04 -1.97151311e+04 -2.26538108e+04
 -2.57965514e+04 -2.91433527e+04 -3.26942149e+04 -3.64491378e+04
 -4.04081216e+04 -4.45711662e+04 -4.89382716e+04 -5.35094378e+04
 -5.82846648e+04 -6.32639527e+04 -6.84473013e+04 -7.38347107e+04
 -7.94261810e+04 -8.52217121e+04 -9.12213039e+04 -9.74249566e+04
 -1.03832670e+05 -1.10444444e+05 -1.17260280e+05 -1.24280175e+05
 -1.31504132e+05 -1.38932150e+05 -1.46564228e+05 -1.54400367e+05
 -1.62440567e+05 -1.70684828e+05 -1.79133150e+05 -1.87785532e+05
 -1.96641975e+05 -2.05702479e+05 -2.14967044e+05 -2.24435670e+05
 -2.34108356e+05 -2.43985104e+05 -2.54065912e+05 -2.64350781e+05
 -2.74839710e+05 -2.85532701e+05 -2.96429752e+05 -3.07530864e+05
 -3.18836037e+05 -3.30345271e+05 -3.42058565e+05 -3.53975921e+05
 -3.66097337e+05 -3.78422

In [ ]:
# Attributes