# Data Alaysis Tutorial

I will be doing a data analysis tutorial so that I can get a firm grasp on `pandas` `numpy` and the `plotly` libraries. The goals of this tutorial will be as follows:

 - Learn how to analyze data statistically using `pandas` and `numpy`.
 - Learn how to vizualize data using `plotly`.
 - Learn how to clean data before analysis.

 I am going to be looking at many sources of data and create data randomly for this project.

 **Let the fun begin.**

In [1]:
import numpy as np
import plotly.express as px
import pandas as pd

In [2]:
# I will be starting off with numpy array.
# ML and Deep Learning has a lot to do with Linear Algebra and Numpy is good.

# np arrays look like a basic python list
# Here is an example

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a[0]) # list indexint still works for np arrays
print(b[0])
print(c.shape) # the.shape attribute will give the dimensions of the array

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

sum_x_y = x + y
print(sum_x_y)

1
5
(3, 3)
[ 6  8 10 12]


In [3]:
# Fill Arrays Automatically

a = np.zeros((5,7,3)) # Gives 5 arrays with a height of 7 and a length of 3
print(a.shape)

b = np.random.random((9,4,2))
print(b)

(5, 7, 3)
[[[0.24430938 0.80088422]
  [0.35338901 0.41173919]
  [0.44815979 0.92022349]
  [0.03248972 0.91065537]]

 [[0.97281643 0.42629888]
  [0.56780927 0.98158925]
  [0.6099349  0.59308477]
  [0.65546497 0.66193101]]

 [[0.89983369 0.49596172]
  [0.75126994 0.79756461]
  [0.52512814 0.85965676]
  [0.11775319 0.17911733]]

 [[0.73723175 0.22924581]
  [0.08944746 0.76432974]
  [0.84321142 0.79657963]
  [0.87476583 0.9480137 ]]

 [[0.74327742 0.32401775]
  [0.26821924 0.39569952]
  [0.340379   0.08362049]
  [0.99085045 0.83176817]]

 [[0.16993723 0.75582126]
  [0.68518387 0.52890839]
  [0.27378974 0.98435902]
  [0.15206674 0.3224248 ]]

 [[0.24675096 0.95127566]
  [0.43096567 0.96970436]
  [0.92307949 0.04870823]
  [0.09943686 0.35331016]]

 [[0.55330667 0.14327319]
  [0.8405391  0.10565959]
  [0.60505572 0.62252285]
  [0.1799072  0.50660816]]

 [[0.20861371 0.27844184]
  [0.38901061 0.92020087]
  [0.10639769 0.31085102]
  [0.65067126 0.71218647]]]


In [6]:
# Rnage Functions

x = np.arange(0,1000,5) # the order is starting val, ending val, step size
y = x*2 - x**2
# print(y)

w = np.linspace(0,1000,100) # starting val, ending val, amount of points specified
z = w*2 - w**2
print(z)

[ 0.00000000e+00 -8.18283849e+01 -3.67717580e+02 -8.57667585e+02
 -1.55167840e+03 -2.44975003e+03 -3.55188246e+03 -4.85807571e+03
 -6.36832976e+03 -8.08264463e+03 -1.00010203e+04 -1.21234568e+04
 -1.44499541e+04 -1.69805122e+04 -1.97151311e+04 -2.26538108e+04
 -2.57965514e+04 -2.91433527e+04 -3.26942149e+04 -3.64491378e+04
 -4.04081216e+04 -4.45711662e+04 -4.89382716e+04 -5.35094378e+04
 -5.82846648e+04 -6.32639527e+04 -6.84473013e+04 -7.38347107e+04
 -7.94261810e+04 -8.52217121e+04 -9.12213039e+04 -9.74249566e+04
 -1.03832670e+05 -1.10444444e+05 -1.17260280e+05 -1.24280175e+05
 -1.31504132e+05 -1.38932150e+05 -1.46564228e+05 -1.54400367e+05
 -1.62440567e+05 -1.70684828e+05 -1.79133150e+05 -1.87785532e+05
 -1.96641975e+05 -2.05702479e+05 -2.14967044e+05 -2.24435670e+05
 -2.34108356e+05 -2.43985104e+05 -2.54065912e+05 -2.64350781e+05
 -2.74839710e+05 -2.85532701e+05 -2.96429752e+05 -3.07530864e+05
 -3.18836037e+05 -3.30345271e+05 -3.42058565e+05 -3.53975921e+05
 -3.66097337e+05 -3.78422