# Numpy Tutorial

I will be doing a data analysis tutorial so that I can get a firm grasp on the `numpy` library. The goals of this tutorial will be as follows:

 - Learn how to analyze data statistically using `numpy`.

 I am going to be looking at many sources of data and create data randomly for this project.

 **Let the fun begin.**

In [2]:
import numpy as np

In [3]:
# I will be starting off with numpy array.
# ML and Deep Learning has a lot to do with Linear Algebra and Numpy is good.

# np arrays look like a basic python list
# Here is an example

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a[0]) # list indexint still works for np arrays
print(b[0])
print(c.shape) # the.shape attribute will give the dimensions of the array

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

sum_x_y = x + y
print(sum_x_y)

1
5
(3, 3)
[ 6  8 10 12]


In [4]:
# Fill Arrays Automatically

a = np.zeros((5,7,3)) # Gives 5 arrays with a height of 7 and a length of 3
print(a.shape)

b = np.random.random((9,4,2))
print(b)

(5, 7, 3)
[[[0.80188478 0.28482891]
  [0.61655373 0.25161785]
  [0.38249498 0.91536763]
  [0.3294675  0.61071231]]

 [[0.36060775 0.62553568]
  [0.66141182 0.17610448]
  [0.3030246  0.26658491]
  [0.48194566 0.01101036]]

 [[0.78112861 0.40381949]
  [0.85143763 0.0348234 ]
  [0.42268595 0.56904857]
  [0.59111448 0.10488212]]

 [[0.90609879 0.66568927]
  [0.80230041 0.94720511]
  [0.56923213 0.43753496]
  [0.11807329 0.7356617 ]]

 [[0.94810885 0.99377952]
  [0.89668968 0.50661668]
  [0.40055598 0.77153509]
  [0.05848411 0.57818454]]

 [[0.28251363 0.28122252]
  [0.65535396 0.92088646]
  [0.65585568 0.5707309 ]
  [0.54032262 0.75478423]]

 [[0.10871845 0.48232521]
  [0.08876519 0.55875316]
  [0.43938674 0.69614528]
  [0.47353849 0.61086809]]

 [[0.24122872 0.15376787]
  [0.12207577 0.09814317]
  [0.44770877 0.81006129]
  [0.03995402 0.00641451]]

 [[0.15868398 0.59511356]
  [0.26722235 0.75031866]
  [0.52757309 0.69774621]
  [0.84272171 0.06350842]]]


In [5]:
# Rnage Functions

x = np.arange(0,1000,5) # the order is starting val, ending val, step size
y = x*2 - x**2
# print(y)

w = np.linspace(0,1000,100) # starting val, ending val, amount of points specified
z = w*2 - w**2
print(z)

[ 0.00000000e+00 -8.18283849e+01 -3.67717580e+02 -8.57667585e+02
 -1.55167840e+03 -2.44975003e+03 -3.55188246e+03 -4.85807571e+03
 -6.36832976e+03 -8.08264463e+03 -1.00010203e+04 -1.21234568e+04
 -1.44499541e+04 -1.69805122e+04 -1.97151311e+04 -2.26538108e+04
 -2.57965514e+04 -2.91433527e+04 -3.26942149e+04 -3.64491378e+04
 -4.04081216e+04 -4.45711662e+04 -4.89382716e+04 -5.35094378e+04
 -5.82846648e+04 -6.32639527e+04 -6.84473013e+04 -7.38347107e+04
 -7.94261810e+04 -8.52217121e+04 -9.12213039e+04 -9.74249566e+04
 -1.03832670e+05 -1.10444444e+05 -1.17260280e+05 -1.24280175e+05
 -1.31504132e+05 -1.38932150e+05 -1.46564228e+05 -1.54400367e+05
 -1.62440567e+05 -1.70684828e+05 -1.79133150e+05 -1.87785532e+05
 -1.96641975e+05 -2.05702479e+05 -2.14967044e+05 -2.24435670e+05
 -2.34108356e+05 -2.43985104e+05 -2.54065912e+05 -2.64350781e+05
 -2.74839710e+05 -2.85532701e+05 -2.96429752e+05 -3.07530864e+05
 -3.18836037e+05 -3.30345271e+05 -3.42058565e+05 -3.53975921e+05
 -3.66097337e+05 -3.78422

In [6]:
# Attributes

a = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [10,20,30],
        [40,50,60]
    ]
])

print(a.shape)

(2, 2, 3)


In [7]:
# Mathematical function in numpy

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(f"{np.std(a):.2f}")

2.58
