# Numpy Tutorial

I will be doing a data analysis tutorial so that I can get a firm grasp on the `numpy` library. The goals of this tutorial will be as follows:

 - Learn how to analyze data statistically using `numpy`.

 I am going to be looking at many sources of data and create data randomly for this project.

 **Let the fun begin.**

In [1]:
import numpy as np

In [3]:
# I will be starting off with numpy array.
# ML and Deep Learning has a lot to do with Linear Algebra and Numpy is good.

# np arrays look like a basic python list
# Here is an example

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a[0]) # list indexint still works for np arrays
print(b[0])
print(c.shape) # the.shape attribute will give the dimensions of the array

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

sum_x_y = x + y
print(sum_x_y)

1
5
(3, 3)
[ 6  8 10 12]


In [4]:
# Fill Arrays Automatically

a = np.zeros((5,7,3)) # Gives 5 arrays with a height of 7 and a length of 3
print(a.shape)

b = np.random.random((9,4,2))
print(b)

(5, 7, 3)
[[[8.69671598e-01 2.42954312e-01]
  [2.40153458e-01 9.57264360e-01]
  [1.17352273e-01 7.94809300e-01]
  [7.90953462e-01 4.94475999e-01]]

 [[8.91326267e-01 6.19065925e-01]
  [2.89306845e-01 9.51825664e-01]
  [6.00323260e-01 6.46095088e-01]
  [7.86333546e-01 1.64087140e-01]]

 [[3.36370620e-02 5.26463166e-01]
  [6.59300841e-01 1.06918865e-01]
  [9.35067471e-01 7.88054571e-01]
  [5.38602438e-01 2.98169517e-01]]

 [[1.90702107e-01 7.39843849e-01]
  [8.62674779e-01 6.51921228e-02]
  [4.58788677e-01 5.14263016e-01]
  [7.37242377e-01 4.67944620e-01]]

 [[6.78515834e-01 3.11568555e-01]
  [8.79457337e-01 2.15873188e-01]
  [4.41774875e-01 5.04902045e-01]
  [8.58879076e-01 7.98451655e-01]]

 [[2.99514905e-02 3.48529711e-01]
  [2.15068969e-01 1.65383569e-01]
  [4.06677423e-01 4.17236267e-01]
  [5.96046017e-01 2.20094489e-01]]

 [[8.91699010e-01 2.21220747e-02]
  [1.97948441e-01 3.58124517e-01]
  [2.43271226e-01 1.09124615e-02]
  [3.45231454e-01 3.95698404e-01]]

 [[1.63927435e-01 5.1749

In [5]:
# Rnage Functions

x = np.arange(0,1000,5) # the order is starting val, ending val, step size
y = x*2 - x**2
# print(y)

w = np.linspace(0,1000,100) # starting val, ending val, amount of points specified
z = w*2 - w**2
print(z)

[ 0.00000000e+00 -8.18283849e+01 -3.67717580e+02 -8.57667585e+02
 -1.55167840e+03 -2.44975003e+03 -3.55188246e+03 -4.85807571e+03
 -6.36832976e+03 -8.08264463e+03 -1.00010203e+04 -1.21234568e+04
 -1.44499541e+04 -1.69805122e+04 -1.97151311e+04 -2.26538108e+04
 -2.57965514e+04 -2.91433527e+04 -3.26942149e+04 -3.64491378e+04
 -4.04081216e+04 -4.45711662e+04 -4.89382716e+04 -5.35094378e+04
 -5.82846648e+04 -6.32639527e+04 -6.84473013e+04 -7.38347107e+04
 -7.94261810e+04 -8.52217121e+04 -9.12213039e+04 -9.74249566e+04
 -1.03832670e+05 -1.10444444e+05 -1.17260280e+05 -1.24280175e+05
 -1.31504132e+05 -1.38932150e+05 -1.46564228e+05 -1.54400367e+05
 -1.62440567e+05 -1.70684828e+05 -1.79133150e+05 -1.87785532e+05
 -1.96641975e+05 -2.05702479e+05 -2.14967044e+05 -2.24435670e+05
 -2.34108356e+05 -2.43985104e+05 -2.54065912e+05 -2.64350781e+05
 -2.74839710e+05 -2.85532701e+05 -2.96429752e+05 -3.07530864e+05
 -3.18836037e+05 -3.30345271e+05 -3.42058565e+05 -3.53975921e+05
 -3.66097337e+05 -3.78422

In [6]:
# Attributes

a = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [10,20,30],
        [40,50,60]
    ]
])

print(a.shape)

(2, 2, 3)


In [13]:
# Mathematical function in numpy

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(f"{np.std(a):.2f}")

2.58
